sudo: required
notifications:
  email:
    on_success: never
    on_failure: never
matrix:
  include:
#    Tests on osx are working but are slow. Uncomment to run them.
#    - language: generic
#      os: osx
#      before_install: # command to install dependencies
#        - brew update
#        # python 2.7.12
#        - virtualenv env -p python
#
#    - language: generic
#      os: osx
#      before_install: # command to install dependencies
#        - brew update
#        # python 3.4.3_2
#        - brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/6051bbe8a67698f3b7e1aad48466c67f77ec04a1/Formula/python3.rb
#        - virtualenv env -p python3
#
#    - language: generic
#      os: osx
#      before_install: # command to install dependencies
#        - brew update
#        # python 3.5.2_3
#        - brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/ec545d45d4512ace3570782283df4ecda6bb0044/Formula/python3.rb
#        - virtualenv env -p python3
#
#    - language: generic
#      os: osx
#      before_install: # command to install dependencies
#        - brew update
#        # python 3.6.1
#        - brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/0c07502e530bae1ca8811a3a27ab0583fbb396b0/Formula/python3.rb
#        - virtualenv env -p python3
#
#    - langage: python
#      python: 2.7
#      os: linux
#      dist: trusty

    - langage: python
      python: 3.4
      os: linux
      dist: trusty

    - langage: python
      python: 3.5
      os: linux
      dist: trusty

    - langage: python
      python: 3.6
      os: linux
      dist: trusty

install: # command to install dependencies
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then source env/bin/activate; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install mpfr; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install libmpc; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install ppl; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get -qq update; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install python-nose; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install python3-pip; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install libgmp-dev; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install libmpfr-dev; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install libmpc-dev; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install libppl-dev; fi
  - pip install --user 'Cython==0.26';
  - pip install --user git+https://github.com/aleaxit/gmpy.git@gmpy2-2.1.0a0 --no-index --verbose;
  - pip install --user cysignals;
  - pip install --user git+https://github.com/jesusjda/pplpy --no-index --verbose
  - pip install --user z3-solver
  - pip install --user git+https://github.com/jesusjda/pyLPi --verbose --no-index;
  - pip install --user pydotplus
  - pip install --user pydot
  - pip install --user matplotlib scipy numpy
  - pip install --user networkx
  - pip install --user arpeggio
  - pip3 install --user pyleri
  - pip install . --user --verbose --no-index;
script: nosetests -v
