sudo: required
notifications:
  email:
    on_success: never
    on_failure: never
matrix:
  include:
#    - langage: python
#      python: 2.7
#      os: linux
#      dist: trusty

    - langage: python
      python: 3.4
      os: linux
      dist: trusty

    - langage: python
      python: 3.5
      os: linux
      dist: trusty

    - langage: python
      python: 3.6
      os: linux
      dist: trusty

install: # command to install dependencies
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get -qq update; fi
#  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install python-nose python3-nose; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install python3-pip; fi
  - pip3 install --user pydotplus
  - pip3 install --user pydot
  - pip3 install --user networkx
  - pip3 install --user arpeggio
  - pip3 install --user pyleri
  - pip3 install . --user --verbose --no-index;
script: 
  - echo "DONE!"
# nosetests-3.3 -v
