#!/bin/bash -e

LLVM2KITTEL=$1
shift
TMPDIR=$1
shift
FILE=$1
shift

NAME=`basename $FILE`

clang -Wall -Wextra -c -emit-llvm -O0 $FILE -o $TMPDIR/$NAME.bc

$TOOLS_HOME/llvm2kittel/build/llvm2kittel --dump-ll --no-slicing --eager-inline $TMPDIR/$NAME.bc -uniform-complexity-tuples 
